default: &default
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>

development:
  <<: *default

test:
  clients:
    default:
      uri: <%= ENV['MONGODB_TEST_URI'] %>

production:
  <<: *default
